name: Release on tag

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: read
  id-token: write

concurrency:
  group: "release-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.CUSTOM_GITHUB_TOKEN}}

      - uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - run: npx changelogithub@0.12 # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{secrets.CUSTOM_GITHUB_TOKEN}}

      - name: Update CHANGELOG.md
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
          push_options: --force

  build-web:
    name: Build Web Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build

      - name: Prepare release zip
        run: |
          set -euo pipefail
          TAG=${{ github.ref_name }}
          ZIP_NAME="release-${TAG}.zip"
          # remove dependency folders and common lockfiles before packaging
          rm -rf node_modules package-lock.json yarn.lock pnpm-lock.yaml npm-shrinkwrap.json || true
          # include build output and public assets (exclude dependency files)
          zip -r "$ZIP_NAME" .next public package.json || true
          ls -lah "$ZIP_NAME"

      - name: Upload web artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-package
          path: release-${{ github.ref_name }}.zip
          if-no-files-found: error

  build-electron-windows:
    name: Build Electron App (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build

      - name: Build Electron app
        run: npm run dist

      - name: List dist contents
        run: |
          ls -la dist/
          find dist/ -type f

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-windows
          path: |
            dist/*.exe
            dist/*.zip
            dist/*.blockmap
            dist/latest*.yml
          if-no-files-found: error

  build-electron-mac:
    name: Build Electron App (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build

      - name: Build Electron app
        run: npm run dist

      - name: List dist contents
        run: |
          ls -la dist/
          find dist/ -type f

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-macos
          path: |
            dist/*.dmg
            dist/*.zip
            dist/*.blockmap
            dist/latest*.yml
          if-no-files-found: error

  build-electron-linux:
    name: Build Electron App (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build

      - name: Build Electron app
        run: npm run dist

      - name: List dist contents
        run: |
          ls -la dist/
          find dist/ -type f

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-linux
          path: |
            dist/*.AppImage
            dist/*.zip
            dist/*.blockmap
            dist/latest*.yml
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: [generate_changelog, build-web, build-electron-windows, build-electron-mac, build-electron-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: List downloaded artifacts
        run: |
          ls -la
          find . -name "*" -type f

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            web-package/release-${{ github.ref_name }}.zip
            electron-windows/*
            electron-macos/*
            electron-linux/*